### PR TITLE
Syntax, style, spaces, spelling

### PR DESCRIPTION
**Pull request by tentena**

### CODE REVIEW

**Comment by tentena** [comment]
There are 67 broken URLs in the README.md. I will create a separate PR for this.

**Comment by tentena** [comment]
Done!

**Comment by Developer-Y** [comment]
Thanks for fixing merge conflicts. I am not sure if it was intentional but after merge, formatting (indentation) of sub-sections was lost. I have reverted PR because it was not clear when a sub-section started

image

In my opinion, indentation is more useful

image

**Comment by tentena** [comment]
Thanks, I'll take a look and create a new PR

**Comment by tentena** [comment]
Created the new one #156 
Kindly check and approve.

**Pull request merged**
